### ISSUE TITLE
minSdk

### ISSUE THREAD

**Issue by ymengx** [iamMehedi/Secured-Preference-Store#4]
这个版本必须18以上才能用吗？

**Comment by iamMehedi** [comment]
@mysprout There is no official `KeyStore` API available before API level 18, that's why this library requires the `minSdk` to be 18 or later. But the `KeyStore` itself might be present on older versions and can be accessed with reflection and private APIs but that shouldn't be tried in production. You can read more about it [here](https://nelenkov.blogspot.jp/2012/05/storing-application-secrets-in-androids.html) if you want.
